"""Add home_type to eco_profiles

Revision ID: 2b341310377b
Revises: 8c7cc3086036
Create Date: 2026-06-28 08:28:46.590767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b341310377b'
down_revision: Union[str, None] = '8c7cc3086036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eco_profiles', sa.Column('home_type', sa.String(length=100), server_default='Apartment', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eco_profiles', 'home_type')
    # ### end Alembic commands ###
