"""Add subscription_tier and ocr_count

Revision ID: d3fee30ca188
Revises: 2b341310377b
Create Date: 2026-06-28 08:37:53.535492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3fee30ca188'
down_revision: Union[str, None] = '2b341310377b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_tier', sa.String(length=20), server_default='free', nullable=False))
    op.add_column('users', sa.Column('ocr_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ocr_count')
    op.drop_column('users', 'subscription_tier')
    # ### end Alembic commands ###
